"""nav tables

Revision ID: 791e06b11b98
Revises: ce9915d16029
Create Date: 2026-10-04 12:49:41.720684
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "791e06b11b98"
down_revision: str | None = "ce9915d16029"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chain_close",
        sa.Column("account", sa.String(length=42), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("chain_id", sa.BigInteger(), nullable=False),
        sa.Column("block", sa.BigInteger(), nullable=False),
        sa.Column("block_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "read_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("account", "day", "chain_id"),
    )
    op.create_table(
        "job_run",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nav_account",
        sa.Column("account", sa.String(length=42), nullable=False),
        sa.Column("start_day", sa.Date(), nullable=False),
        sa.Column("notes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("account"),
    )
    op.create_table(
        "nav_day",
        sa.Column("account", sa.String(length=42), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("nav_micro", sa.BigInteger(), nullable=True),
        sa.Column("flow_micro", sa.BigInteger(), nullable=True),
        sa.Column("units", sa.Numeric(precision=40, scale=0), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=40, scale=0), nullable=True),
        sa.Column("yield_micro", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("account", "day"),
    )
    op.create_table(
        "position_close",
        sa.Column("account", sa.String(length=42), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("chain_id", sa.BigInteger(), nullable=False),
        sa.Column("instrument_id", sa.Text(), nullable=False),
        sa.Column("protocol", sa.Text(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("shares_raw", sa.Numeric(precision=78, scale=0), nullable=False),
        sa.Column("base_shares_raw", sa.Numeric(precision=78, scale=0), nullable=True),
        sa.Column("underlying_raw", sa.Numeric(precision=78, scale=0), nullable=True),
        sa.Column("decimals", sa.Integer(), nullable=True),
        sa.Column("price_usd", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("price_source", sa.String(length=16), nullable=True),
        sa.Column("usd_micro", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("account", "day", "chain_id", "instrument_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("position_close")
    op.drop_table("nav_day")
    op.drop_table("nav_account")
    op.drop_table("job_run")
    op.drop_table("chain_close")
    # ### end Alembic commands ###
