"""position yield and loop debt

Revision ID: 4e87e4192bf5
Revises: 791e06b11b98
Create Date: 2026-10-05 11:55:57.703949
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4e87e4192bf5"
down_revision: str | None = "791e06b11b98"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "position_yield",
        sa.Column("account", sa.String(length=42), nullable=False),
        sa.Column("chain_id", sa.BigInteger(), nullable=False),
        sa.Column("instrument_id", sa.Text(), nullable=False),
        sa.Column("protocol", sa.Text(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("yield_micro", sa.BigInteger(), nullable=False),
        sa.Column("unknown_days", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("account", "chain_id", "instrument_id"),
    )
    op.add_column(
        "position_close",
        sa.Column("debt_shares_raw", sa.Numeric(precision=78, scale=0), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("position_close", "debt_shares_raw")
    op.drop_table("position_yield")
    # ### end Alembic commands ###
