/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plans
         * @description The most recently proposed plans, newest first.
         */
        get: operations["list_plans_api_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plan
         * @description The stored plan an approval would apply. Show this, not the model's copy.
         */
        get: operations["get_plan_api_plans__plan_hash__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Plan
         * @description Apply the stored plan with this hash, once, after a policy re-check.
         */
        post: operations["approve_plan_api_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Plan
         * @description Retire the stored plan with this hash without applying it.
         */
        post: operations["reject_plan_api_reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Book
         * @description The account's positions and idle cash, read live (cached a minute).
         */
        get: operations["get_book_api_book_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nav": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Nav
         * @description The NAV history the backfill has derived, and what it could not read.
         */
        get: operations["get_nav_api_nav_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nav/backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Backfill
         * @description Read any closed day still missing, then rebuild NAV, in the background.
         */
        post: operations["start_backfill_api_nav_backfill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Jobs */
        get: operations["get_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveResponse */
        ApproveResponse: {
            /** Plan Hash */
            plan_hash: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
        };
        /** BackfillResponse */
        BackfillResponse: {
            /** Started */
            started: boolean;
        };
        /** BookPosition */
        BookPosition: {
            /** Instrument Id */
            instrument_id: string;
            /** Protocol */
            protocol: string;
            /** Chain Id */
            chain_id: number;
            /** Chain */
            chain: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Yield Token Symbol */
            yield_token_symbol: string | null;
            /** Usd */
            usd: number;
            /** Weight */
            weight: number;
            /** Apy */
            apy: number | null;
            /** Leverage */
            leverage: number | null;
        };
        /** BookResponse */
        BookResponse: {
            /** Account */
            account: string;
            /**
             * Read At
             * Format: date-time
             */
            read_at: string;
            /** Total Usd */
            total_usd: number;
            /** Deployed Usd */
            deployed_usd: number;
            /** Idle Usd */
            idle_usd: number;
            /** Blended Apy */
            blended_apy: number | null;
            /** Income Per Year Usd */
            income_per_year_usd: number | null;
            /** Effective Positions */
            effective_positions: number | null;
            /** Positions */
            positions: components["schemas"]["BookPosition"][];
            /** Idle */
            idle: components["schemas"]["IdleBalance"][];
            /** By Protocol */
            by_protocol: components["schemas"]["BookSlice"][];
            /** By Chain */
            by_chain: components["schemas"]["BookSlice"][];
            /** Warnings */
            warnings: string[];
        };
        /** BookSlice */
        BookSlice: {
            /** Label */
            label: string;
            /** Usd */
            usd: number;
            /** Weight */
            weight: number;
        };
        /** BridgeReview */
        BridgeReview: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "bridge";
            /** Account */
            account: string;
            /** From Chain Id */
            from_chain_id: number;
            /** To Chain Id */
            to_chain_id: number;
            /** Amount Usdc */
            amount_usdc: number;
            /** Ref */
            ref: string | null;
            /** Advances */
            advances: {
                [key: string]: unknown;
            } | null;
            /** Bundles */
            bundles: components["schemas"]["ReviewBundle"][];
            /** Funding */
            funding: components["schemas"]["ReviewFunding"][];
            /** Notes */
            notes: string[];
            /** Blockers */
            blockers: string[];
            /** Transactions */
            transactions: number;
        };
        /** ExecuteReview */
        ExecuteReview: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "execute";
            /** Account */
            account: string;
            /** Target Usd */
            target_usd: number | null;
            /** Deposit Usd */
            deposit_usd: number;
            /** Legs */
            legs: components["schemas"]["ReviewLeg"][];
            /** Bundles */
            bundles: components["schemas"]["ReviewBundle"][];
            /** Loops */
            loops: {
                [key: string]: unknown;
            }[];
            /** Funding */
            funding: components["schemas"]["ReviewFunding"][];
            policy: components["schemas"]["ReviewPolicy"];
            /** Notes */
            notes: string[];
            /** Blockers */
            blockers: string[];
            /** Transactions */
            transactions: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IdleBalance */
        IdleBalance: {
            /** Chain Id */
            chain_id: number;
            /** Chain */
            chain: string;
            /** Usd */
            usd: number;
        };
        /** JobRun */
        JobRun: {
            /** Id */
            id: number;
            /** Job */
            job: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Status */
            status: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            } | null;
        };
        /** LoopCloseReview */
        LoopCloseReview: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "loop-close";
            /** Account */
            account: string;
            /** Loop Id */
            loop_id: string;
            /** Bundles */
            bundles: components["schemas"]["ReviewBundle"][];
            /** Loop */
            loop: {
                [key: string]: unknown;
            };
            /** Transactions */
            transactions: number;
        };
        /** LoopOpenReview */
        LoopOpenReview: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "loop-open";
            /** Account */
            account: string;
            /** Loop Id */
            loop_id: string;
            /** Equity Usd */
            equity_usd: number;
            /** Leverage */
            leverage: number;
            /** Bundles */
            bundles: components["schemas"]["ReviewBundle"][];
            /** Loop */
            loop: {
                [key: string]: unknown;
            };
            policy: components["schemas"]["ReviewPolicy"];
            /** Notes */
            notes: string[];
            /** Transactions */
            transactions: number;
        };
        /** NavChain */
        NavChain: {
            /** Chain Id */
            chain_id: number;
            /** Chain */
            chain: string;
            /** Days Read */
            days_read: number;
            /** Days Unknown */
            days_unknown: number;
            /** First Day */
            first_day: string | null;
            /** Last Day */
            last_day: string | null;
            /** Error */
            error: string | null;
        };
        /** NavPoint */
        NavPoint: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Nav Usd */
            nav_usd: number | null;
            /** Flow Usd */
            flow_usd: number | null;
            /** Unit Price */
            unit_price: number | null;
            /** Yield Usd */
            yield_usd: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "opened" | "unknown" | "empty";
            /** Reason */
            reason: string | null;
        };
        /** NavResponse */
        NavResponse: {
            /** Account */
            account: string;
            /** Start Day */
            start_day: string | null;
            /** Start Notes */
            start_notes: string[];
            /** Days */
            days: components["schemas"]["NavPoint"][];
            /** Chains */
            chains: components["schemas"]["NavChain"][];
            summary: components["schemas"]["NavSummary"];
            last_run: components["schemas"]["JobRun"] | null;
            /** Backfilling */
            backfilling: boolean;
        };
        /** NavSummary */
        NavSummary: {
            /** Since */
            since: string | null;
            /** Last Day */
            last_day: string | null;
            /** Unit Price */
            unit_price: number | null;
            /** Nav Usd */
            nav_usd: number | null;
            /** Total Return */
            total_return: number | null;
            /** Annualized Return */
            annualized_return: number | null;
            /** Yield Usd */
            yield_usd: number;
            /** Net Flow Usd */
            net_flow_usd: number;
            /** Days */
            days: number;
            /** Unknown Days */
            unknown_days: number;
        };
        /** PlanHashRequest */
        PlanHashRequest: {
            /** Plan Hash */
            plan_hash: string;
        };
        /** PlanResponse */
        PlanResponse: {
            /** Plan Hash */
            plan_hash: string;
            /** Kind */
            kind: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "expired" | "applying" | "applied" | "failed" | "rejected";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Review */
            review: (components["schemas"]["ExecuteReview"] | components["schemas"]["WithdrawReview"] | components["schemas"]["RebalanceReview"] | components["schemas"]["LoopOpenReview"] | components["schemas"]["LoopCloseReview"] | components["schemas"]["BridgeReview"]) | null;
            /** Review Error */
            review_error: string | null;
            /** Plan */
            plan: {
                [key: string]: unknown;
            };
            /** Used At */
            used_at: string | null;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string | null;
        };
        /** PlanSummary */
        PlanSummary: {
            /** Plan Hash */
            plan_hash: string;
            /** Kind */
            kind: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "expired" | "applying" | "applied" | "failed" | "rejected";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** RebalanceReview */
        RebalanceReview: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "rebalance";
            /** Account */
            account: string;
            /** Book Usd */
            book_usd: number;
            /** Target Usd */
            target_usd: number | null;
            /** Total Sell Usd */
            total_sell_usd: number;
            /** Total Buy Usd */
            total_buy_usd: number;
            /** Min Trade Usd */
            min_trade_usd: number;
            /** Trades */
            trades: components["schemas"]["ReviewTrade"][];
            /** Skipped */
            skipped: components["schemas"]["ReviewSkipped"][];
            /** Bundles */
            bundles: components["schemas"]["ReviewBundle"][];
            /** Funding */
            funding: components["schemas"]["ReviewFunding"][];
            policy: components["schemas"]["ReviewPolicy"];
            /** Notes */
            notes: string[];
            /** Blockers */
            blockers: string[];
            /** Transactions */
            transactions: number;
        };
        /** RejectResponse */
        RejectResponse: {
            /** Plan Hash */
            plan_hash: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "expired" | "applying" | "applied" | "failed" | "rejected";
        };
        /** ReviewBridge */
        ReviewBridge: {
            /** To Chain Id */
            to_chain_id: number;
            /** Fast */
            fast: boolean;
            max_fee: components["schemas"]["TokenAmount"] | null;
        };
        /** ReviewBundle */
        ReviewBundle: {
            /** Bundle Id */
            bundle_id: string;
            /** Leg Index */
            leg_index: number;
            /** Instrument Id */
            instrument_id: string;
            /** Action */
            action: string;
            /** Chain Id */
            chain_id: number;
            amount_in: components["schemas"]["TokenAmount"] | null;
            expected_out: components["schemas"]["TokenAmount"] | null;
            min_out: components["schemas"]["TokenAmount"] | null;
            /** Steps */
            steps: string[];
            /** Expires At */
            expires_at: number | null;
            bridge: components["schemas"]["ReviewBridge"] | null;
        };
        /** ReviewFunding */
        ReviewFunding: {
            /** Chain Id */
            chain_id: number;
            required: components["schemas"]["TokenAmount"] | null;
            available: components["schemas"]["TokenAmount"] | null;
            shortfall: components["schemas"]["TokenAmount"] | null;
            /** Includes Gas Charge */
            includes_gas_charge: boolean;
            /** Ok */
            ok: boolean;
        };
        /** ReviewLeg */
        ReviewLeg: {
            /** Leg Index */
            leg_index: number;
            /** Instrument Id */
            instrument_id: string;
            /** Target Usd */
            target_usd: number | null;
            /** Deposit Usd */
            deposit_usd: number | null;
            /** Leverage */
            leverage: number | null;
        };
        /** ReviewPolicy */
        ReviewPolicy: {
            /** Ok */
            ok: boolean;
            /** Violations */
            violations: components["schemas"]["ReviewViolation"][];
        };
        /** ReviewSkipped */
        ReviewSkipped: {
            /** Instrument Id */
            instrument_id: string;
            /**
             * Action
             * @enum {string}
             */
            action: "sell" | "buy";
            /** Delta Usd */
            delta_usd: number;
        };
        /** ReviewTrade */
        ReviewTrade: {
            /** Trade Index */
            trade_index: number;
            /** Instrument Id */
            instrument_id: string;
            /**
             * Action
             * @enum {string}
             */
            action: "sell" | "buy";
            /** Usd */
            usd: number;
            /** Current Usd */
            current_usd: number;
            /** Target Usd */
            target_usd: number;
            /** Current Weight */
            current_weight: number;
            /** Target Weight */
            target_weight: number;
            /** Deposit Usd */
            deposit_usd: number | null;
        };
        /** ReviewViolation */
        ReviewViolation: {
            /** Rule */
            rule: string;
            /** Entity */
            entity: string;
            /** Limit */
            limit: unknown;
            /** Actual */
            actual: unknown;
        };
        /** TokenAmount */
        TokenAmount: {
            /** Raw */
            raw: string;
            /** Amount */
            amount: string | null;
            /** Symbol */
            symbol: string | null;
            /** Token */
            token: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WithdrawReview */
        WithdrawReview: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "withdraw";
            /** Account */
            account: string;
            /** Instrument Id */
            instrument_id: string;
            /** Protocol */
            protocol: string;
            /** Chain Id */
            chain_id: number;
            /** Symbol */
            symbol: string;
            /** Full Exit */
            full_exit: boolean;
            /** Requested Usd */
            requested_usd: number | null;
            /** Current Usd */
            current_usd: number;
            /** Shares */
            shares: string;
            /** Share Balance */
            share_balance: string;
            /** Share Symbol */
            share_symbol: string | null;
            /** Expected Usdc */
            expected_usdc: string | null;
            /** Bundles */
            bundles: components["schemas"]["ReviewBundle"][];
            /** Funding */
            funding: components["schemas"]["ReviewFunding"][];
            /** Notes */
            notes: string[];
            /** Blockers */
            blockers: string[];
            /** Transactions */
            transactions: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_plans_api_plans_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_plans__plan_hash__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_plan_api_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanHashRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_plan_api_reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanHashRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RejectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_api_book_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_nav_api_nav_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavResponse"];
                };
            };
        };
    };
    start_backfill_api_nav_backfill_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackfillResponse"];
                };
            };
        };
    };
    get_jobs_api_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRun"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
