/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plans
         * @description The most recently proposed plans, newest first.
         */
        get: operations["list_plans_api_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plan
         * @description The stored plan an approval would apply. Show this, not the model's copy.
         */
        get: operations["get_plan_api_plans__plan_hash__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Plan
         * @description Apply the stored plan with this hash, once, after a policy re-check.
         */
        post: operations["approve_plan_api_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Plan
         * @description Retire the stored plan with this hash without applying it.
         */
        post: operations["reject_plan_api_reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveResponse */
        ApproveResponse: {
            /** Plan Hash */
            plan_hash: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
        };
        /** ExecuteReview */
        ExecuteReview: {
            /**
             * Kind
             * @constant
             */
            kind: "execute";
            /** Account */
            account: string;
            /** Target Usd */
            target_usd: number | null;
            /** Deposit Usd */
            deposit_usd: number;
            /** Legs */
            legs: components["schemas"]["ReviewLeg"][];
            /** Bundles */
            bundles: components["schemas"]["ReviewBundle"][];
            /** Loops */
            loops: {
                [key: string]: unknown;
            }[];
            /** Funding */
            funding: components["schemas"]["ReviewFunding"][];
            policy: components["schemas"]["ReviewPolicy"];
            /** Notes */
            notes: string[];
            /** Blockers */
            blockers: string[];
            /** Transactions */
            transactions: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PlanHashRequest */
        PlanHashRequest: {
            /** Plan Hash */
            plan_hash: string;
        };
        /** PlanResponse */
        PlanResponse: {
            /** Plan Hash */
            plan_hash: string;
            /** Kind */
            kind: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "expired" | "applying" | "applied" | "failed" | "rejected";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            review: components["schemas"]["ExecuteReview"] | null;
            /** Review Error */
            review_error: string | null;
            /** Plan */
            plan: {
                [key: string]: unknown;
            };
            /** Used At */
            used_at: string | null;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string | null;
        };
        /** PlanSummary */
        PlanSummary: {
            /** Plan Hash */
            plan_hash: string;
            /** Kind */
            kind: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "expired" | "applying" | "applied" | "failed" | "rejected";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** RejectResponse */
        RejectResponse: {
            /** Plan Hash */
            plan_hash: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "expired" | "applying" | "applied" | "failed" | "rejected";
        };
        /** ReviewBridge */
        ReviewBridge: {
            /** To Chain Id */
            to_chain_id: number;
            /** Fast */
            fast: boolean;
            max_fee: components["schemas"]["TokenAmount"] | null;
        };
        /** ReviewBundle */
        ReviewBundle: {
            /** Bundle Id */
            bundle_id: string;
            /** Leg Index */
            leg_index: number;
            /** Instrument Id */
            instrument_id: string;
            /** Action */
            action: string;
            /** Chain Id */
            chain_id: number;
            amount_in: components["schemas"]["TokenAmount"] | null;
            expected_out: components["schemas"]["TokenAmount"] | null;
            min_out: components["schemas"]["TokenAmount"] | null;
            /** Steps */
            steps: string[];
            /** Expires At */
            expires_at: number | null;
            bridge: components["schemas"]["ReviewBridge"] | null;
        };
        /** ReviewFunding */
        ReviewFunding: {
            /** Chain Id */
            chain_id: number;
            required: components["schemas"]["TokenAmount"] | null;
            available: components["schemas"]["TokenAmount"] | null;
            shortfall: components["schemas"]["TokenAmount"] | null;
            /** Includes Gas Charge */
            includes_gas_charge: boolean;
            /** Ok */
            ok: boolean;
        };
        /** ReviewLeg */
        ReviewLeg: {
            /** Leg Index */
            leg_index: number;
            /** Instrument Id */
            instrument_id: string;
            /** Target Usd */
            target_usd: number | null;
            /** Deposit Usd */
            deposit_usd: number | null;
            /** Leverage */
            leverage: number | null;
        };
        /** ReviewPolicy */
        ReviewPolicy: {
            /** Ok */
            ok: boolean;
            /** Violations */
            violations: components["schemas"]["ReviewViolation"][];
        };
        /** ReviewViolation */
        ReviewViolation: {
            /** Rule */
            rule: string;
            /** Entity */
            entity: string;
            /** Limit */
            limit: unknown;
            /** Actual */
            actual: unknown;
        };
        /** TokenAmount */
        TokenAmount: {
            /** Raw */
            raw: string;
            /** Amount */
            amount: string | null;
            /** Symbol */
            symbol: string | null;
            /** Token */
            token: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_plans_api_plans_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_plans__plan_hash__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_plan_api_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanHashRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_plan_api_reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanHashRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RejectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
